import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class LanguageProvider with ChangeNotifier {
  Locale _locale = const Locale('pt', 'BR');

  Locale get locale => _locale;

  void setLanguage(String languageCode) {
    if (languageCode == 'pt') {
      _locale = const Locale('pt', 'BR');
    } else {
      _locale = const Locale('en', 'US');
    }
    notifyListeners();
  }

  static Map<String, Map<String, String>> translations = {
    'pt': {
      'nav.myTrips': 'Minhas Viagens',
      'nav.groups': 'Grupos',
      'nav.feed': 'Feed',
      'nav.profile': 'Perfil',
      'nav.settings': 'Configurações',
      'nav.signOut': 'Sair',
      'config.title': 'Configurações da Conta',
      'config.info': 'Informações da Conta',
      'config.name': 'Nome',
      'config.email': 'E-mail',
      'config.save': 'Salvar Alterações',
      'config.danger': 'Zona de Perigo',
      'config.delete': 'Excluir Conta',
      'config.deleteConfirmTitle': 'Excluir Conta?',
      'config.deleteConfirmDesc': 'Esta ação é permanente. Todos os seus dados serão removidos. Continuar?',
      'config.cancel': 'Cancelar',
      'config.saved': 'Alterações salvas!',
      'language.select': 'Idioma',
      'language.pt': 'Português (Brasil)',
      'language.en': 'English (United States)',
      'lobby.greeting': 'Olá, {name}! 👋',
      'lobby.aiAssistant': 'Assistente de Viagem IA',
      'lobby.newTrip': 'Nova Viagem',
      'lobby.noTrips': 'Nenhuma viagem ainda',
      'lobby.createFirst': 'Crie sua primeira viagem',
      'lobby.selectTrip': 'Selecione uma viagem para começar a conversar',
      'lobby.thinking': 'Pensando...',
      'lobby.hint': 'Pergunte qualquer coisa sobre sua viagem...',
      'viagem.title': 'Viagem',
      'viagem.error': 'Falha ao carregar dados da viagem.',
      'viagem.retry': 'Tentar novamente',
      'viagem.tabs.overview': 'Visão Geral',
      'viagem.tabs.finances': 'Minhas Finanças',
      'viagem.tabs.admin': 'Admin',
      'viagem.tabs.expenses': 'Gastos',
      'viagem.tabs.itinerary': 'Roteiro',
      'viagem.tabs.photos': 'Fotos',
      'viagem.tabs.chat': 'Chat',
      'config.saved': 'Alterações salvas!',
      'viagem.value.placeholder': 'Valor...',
      'expenses.edit': 'Editar Gasto',
      'expenses.value': 'Valor (R\$)',
      'expenses.category': 'Categoria',
      'expenses.description': 'Descrição',
      'expenses.descriptionHint': 'Descrição (opcional)',
      'expenses.cancel': 'Cancelar',
      'expenses.save': 'Salvar',
      'expenses.date': 'Data',
      'expenses.splitWith': 'Dividir com:',
      'expenses.splitNone': 'Ninguém selecionado → dividir igualmente entre todos os {count} membros',
      'expenses.splitSelected': 'Dividindo entre {count} membro(s) selecionado(s)',
      'expenses.add': 'Adicionar Gasto',
      'expenses.empty': 'Nenhum gasto ainda.',
      'expenses.deleteError': 'Erro ao deletar gasto: {error}',

      'admin.required': 'Acesso de administrador necessário',
      'admin.statistics': 'Estatísticas',
      'admin.activeMembers': 'Membros Ativos',
      'admin.photos': 'Fotos',
      'admin.itinerary': 'Roteiro',
      'admin.ranking': 'Ranking Financeiro',
      'admin.members': 'Membros',
      'admin.promote': 'Promover a admin',
      'admin.demote': 'Remover admin',
      'admin.you': 'Você',
      'overview.totalSpent': 'Total Gasto',
      'overview.remainingBudget': 'Orçamento Restante',
      'overview.used': 'usado',
      'overview.byCategory': 'Por Categoria',
      'finances.paid': 'Eu paguei',
      'finances.debt': 'Minha dívida',
      'finances.recentExpenses': 'Gastos Recentes',
      'itinerary.add': 'Adicionar Item',
      'itinerary.edit': 'Editar Item',
      'itinerary.title': 'Título',
      'itinerary.description': 'Descrição',
      'itinerary.cancel': 'Cancelar',
      'itinerary.save': 'Salvar',
      'itinerary.empty': 'Nenhum item no roteiro ainda.',
      'chat.hint': 'Mensagem...',
      'chat.thinking': 'Pensando...',
      'perfil.myProfile': 'Meu Perfil',
      'perfil.profile': 'Perfil',
      'perfil.posts': 'Postagens',
      'perfil.followers': 'Seguidores',
      'perfil.following': 'Seguindo',
      'perfil.follow': 'Seguir',
      'perfil.followingBtn': 'Seguindo',
      'perfil.editProfile': 'Editar Perfil',
      'perfil.cancel': 'Cancelar',
      'perfil.save': 'Salvar',
      'perfil.name': 'Nome',
      'perfil.bio': 'Bio',
      'perfil.memberSince': 'Membro desde',
      'perfil.noPosts': 'Nenhuma postagem ainda.',
      'perfil.deletePost': 'Excluir post',
      'perfil.comments': 'Comentários',
      'perfil.like': 'curtida',
      'perfil.likes': 'curtidas',
      'perfil.addComment': 'Adicionar um comentário...',
      'perfil.post': 'Publicar',
      'perfil.noUsers': 'Nenhum usuário ainda.',
      'feed.addComment': 'Escreva um comentário...',
      'feed.viewAll': 'Ver todos os {count} comentário(s)',
      'feed.deleteTitle': 'Excluir post?',
      'feed.deleteCancel': 'Cancelar',
      'feed.deleteConfirm': 'Excluir',
      'grupos.title': 'Grupos',
      'grupos.newTrip': 'Nova Viagem',
      'grupos.joinTitle': 'Entrar em um grupo',
      'grupos.joinDesc': 'Digite o código de convite para entrar em uma viagem existente.',
      'grupos.codeHint': 'Código de convite',
      'grupos.joinBtn': 'Entrar',
      'grupos.search': 'Pesquisar grupos...',
      'grupos.searchResults': 'Resultados da Busca',
      'grupos.myTrips': 'Minhas Viagens',
      'grupos.tapHint': 'Toque para conversar com a IA  ·  Segure para detalhes',
      'grupos.noGroups': 'Nenhum grupo encontrado.',
      'grupos.noTrips': 'Nenhuma viagem ainda.',
      'grupos.invalidCode': 'Código inválido',
      'grupos.joinSuccess': 'Entrou no grupo com sucesso!',
      'formViagem.tripName': 'Nome da viagem',
      'formViagem.destination': 'Destino',
      'formViagem.startDate': 'Data de início',
      'formViagem.endDate': 'Data de fim',
      'formViagem.budget': 'Orçamento (R\$)',
      'formViagem.tripType': 'Tipo de viagem',
      'formViagem.preferences': 'Preferências (opcional)',
      'formViagem.createBtn': 'Criar viagem',
      'formViagem.required': 'Campo obrigatório',
      'formViagem.invalidValue': 'Valor inválido',
      'photos.deleteTitle': 'Excluir foto?',
      'photos.deleteDesc': 'Essa ação não pode ser desfeita.',
      'photos.cancel': 'Cancelar',
      'photos.delete': 'Excluir',
      'photos.empty': 'Nenhuma foto ainda.',
      'photos.hint': 'Toque + para adicionar a primeira.',
      'photos.addTooltip': 'Adicionar foto',
      'login.subtitle': 'Planejamento de Viagens com IA',
      'login.password': 'Senha',
      'login.passwordRequired': 'Digite a senha',
      'login.signIn': 'Entrar',
      'login.noAccount': 'Não tem uma conta? ',
      'login.signUp': 'Cadastrar-se',
      'login.emailInvalid': 'E-mail inválido',
      'register.title': 'Criar Conta',
      'register.fullName': 'Nome Completo',
      'register.minChars': 'Mínimo 3 caracteres',
      'register.min8chars': 'Mínimo 8 caracteres',
      'register.needUppercase': 'Precisa de uma maiúscula',
      'register.needNumber': 'Precisa de um número',
      'register.hasAccount': 'Já tem uma conta? ',
      'feed.noPostsYet': 'Nenhuma postagem ainda. Seja o primeiro!',
      'feed.newPostTooltip': 'Novo post',
      'feed.createHint': 'O que você está pensando sobre a sua viagem?',
      'feed.share': 'Compartilhar',
      'feed.loadError': 'Erro ao carregar o feed. Verifique sua conexão.',
      'feed.retry': 'Tentar novamente',
      'formViagem.selectDates': 'Selecione as datas de início e fim',
      'grupos.openTrip': 'Abrir viagem',
      'grupos.openTripFull': 'Abrir viagem completa',
      'grupos.iaHint': 'Pergunte sobre a viagem...',
      'grupos.iaEmptyHint': 'Pergunte qualquer coisa sobre\nsua viagem e o destino',
      'grupos.iaError': 'Não foi possível obter resposta. Tente novamente.',
      'grupos.chatIA': 'Chat IA',
      'grupos.codeCopied': 'Código copiado!',
      'grupos.inviteCode': 'Código de convite',
      'grupos.period': 'Período',
      'grupos.budgetLabel': 'Orçamento',
      'grupos.type': 'Tipo',
      'grupos.preferencesLabel': 'Preferências',
      'grupos.tbd': 'a definir',
      'grupos.suggest1': 'O que levar nessa viagem?',
      'grupos.suggest2': 'Dicas de orçamento',
      'grupos.suggest3': 'Pontos turísticos imperdíveis',
      'grupos.suggest4': 'Melhor época para ir',
      'info.destination': 'Destino',
      'info.period': 'Período',
      'info.budget': 'Orçamento',
      'info.type': 'Tipo',
      'info.preferences': 'Preferências',
      'info.aiTipsTitle': 'Dicas do Assistente IA',
      'info.aiTipsSubtitle': 'Experimente perguntar ao assistente:',
      'info.inviteCode': 'Código de convite',
      'info.codeCopied': 'Código copiado!',
      'info.aiTip1': '"Quais são os melhores restaurantes em [destino]?"',
      'info.aiTip2': '"Sugira um roteiro de 3 dias para nossa viagem."',
      'info.aiTip3': '"O que devemos levar para esse tipo de viagem?"',
      'info.aiTip4': '"Como podemos dividir os custos de forma justa no grupo?"',
      'info.aiTip5': '"Quais atrações imperdíveis há perto de [destino]?"',
      'info.aiTip6': '"Alguma dica de costumes locais que devemos saber?"',
      'cropper.title': 'Recortar Foto',
      'cropper.usePhoto': '✓ Usar esta foto',
      'cropper.cancel': 'Cancelar',
    },
    'en': {
      'nav.myTrips': 'My Trips',
      'nav.groups': 'Groups',
      'nav.feed': 'Feed',
      'nav.profile': 'Profile',
      'nav.settings': 'Settings',
      'nav.signOut': 'Sign Out',
      'config.title': 'Account Settings',
      'config.info': 'Account Information',
      'config.name': 'Name',
      'config.email': 'Email',
      'config.save': 'Save Changes',
      'config.danger': 'Danger Zone',
      'config.delete': 'Delete Account',
      'config.deleteConfirmTitle': 'Delete Account',
      'config.deleteConfirmDesc': 'This action is permanent. All your data will be removed. Continue?',
      'config.cancel': 'Cancel',
      'config.saved': 'Changes saved!',
      'language.select': 'Language',
      'language.pt': 'Portuguese (Brasil)',
      'language.en': 'English (United States)',
      'lobby.greeting': 'Hello, {name}! 👋',
      'lobby.aiAssistant': 'AI Travel Assistant',
      'lobby.newTrip': 'New Trip',
      'lobby.noTrips': 'No trips yet',
      'lobby.createFirst': 'Create your first trip',
      'lobby.selectTrip': 'Select a trip to start chatting',
      'lobby.thinking': 'Thinking...',
      'lobby.hint': 'Ask anything about your trip...',
      'viagem.title': 'Trip',
      'viagem.error': 'Failed to load trip data.',
      'viagem.retry': 'Retry',
      'viagem.tabs.overview': 'Overview',
      'viagem.tabs.finances': 'My Finances',
      'viagem.tabs.admin': 'Admin',
      'viagem.tabs.expenses': 'Expenses',
      'viagem.tabs.itinerary': 'Itinerary',
      'viagem.tabs.photos': 'Photos',
      'viagem.tabs.chat': 'Chat',
      'viagem.tabs.info': 'Info',
      'viagem.value.placeholder': 'Value...',
      'expenses.edit': 'Edit Expense',
      'expenses.value': 'Value (R\$)',
      'expenses.category': 'Category',
      'expenses.description': 'Description',
      'expenses.descriptionHint': 'Description (optional)',
      'expenses.cancel': 'Cancel',
      'expenses.save': 'Save',
      'expenses.date': 'Date',
      'expenses.splitWith': 'Split with:',
      'expenses.splitNone': 'No one selected → split equally among all {count} members',
      'expenses.splitSelected': 'Splitting among {count} selected member(s)',
      'expenses.add': 'Add Expense',
      'expenses.empty': 'No expenses yet.',
      'expenses.deleteError': 'Error deleting expense: {error}',
      'admin.required': 'Admin access required',
      'admin.statistics': 'Statistics',
      'admin.activeMembers': 'Active Members',
      'admin.photos': 'Photos',
      'admin.itinerary': 'Itinerary',
      'admin.ranking': 'Financial Ranking',
      'admin.members': 'Members',
      'admin.promote': 'Promote to admin',
      'admin.demote': 'Remove admin',
      'admin.you': 'You',
      'overview.totalSpent': 'Total Spent',
      'overview.remainingBudget': 'Remaining Budget',
      'overview.used': 'used',
      'overview.byCategory': 'By Category',
      'finances.paid': 'I paid',
      'finances.debt': 'My debt',
      'finances.recentExpenses': 'Recent Expenses',
      'itinerary.add': 'Add Item',
      'itinerary.edit': 'Edit Item',
      'itinerary.title': 'Title',
      'itinerary.description': 'Description',
      'itinerary.cancel': 'Cancel',
      'itinerary.save': 'Save',
      'itinerary.empty': 'No itinerary items yet.',
      'chat.hint': 'Message...',
      'chat.thinking': 'Thinking...',
      'perfil.myProfile': 'My Profile',
      'perfil.profile': 'Profile',
      'perfil.posts': 'Posts',
      'perfil.followers': 'Followers',
      'perfil.following': 'Following',
      'perfil.follow': 'Follow',
      'perfil.followingBtn': 'Following',
      'perfil.editProfile': 'Edit Profile',
      'perfil.cancel': 'Cancel',
      'perfil.save': 'Save',
      'perfil.name': 'Name',
      'perfil.bio': 'Bio',
      'perfil.memberSince': 'Member since',
      'perfil.noPosts': 'No posts yet.',
      'perfil.deletePost': 'Delete post',
      'perfil.comments': 'Comments',
      'perfil.like': 'like',
      'perfil.likes': 'likes',
      'perfil.addComment': 'Add a comment...',
      'perfil.post': 'Post',
      'perfil.noUsers': 'No users yet.',
      'feed.addComment': 'Write a comment...',
      'feed.viewAll': 'View all {count} comment(s)',
      'feed.deleteTitle': 'Delete post?',
      'feed.deleteCancel': 'Cancel',
      'feed.deleteConfirm': 'Delete',
      'grupos.title': 'Groups',
      'grupos.newTrip': 'New Trip',
      'grupos.joinTitle': 'Join a group',
      'grupos.joinDesc': 'Enter the invite code to join an existing trip.',
      'grupos.codeHint': 'Invite code',
      'grupos.joinBtn': 'Join',
      'grupos.search': 'Search groups...',
      'grupos.searchResults': 'Search Results',
      'grupos.myTrips': 'My Trips',
      'grupos.tapHint': 'Tap to chat with AI  ·  Hold for trip details',
      'grupos.noGroups': 'No groups found.',
      'grupos.noTrips': 'No trips yet.',
      'grupos.invalidCode': 'Invalid code',
      'grupos.joinSuccess': 'Joined the group successfully!',
      'formViagem.tripName': 'Trip Name',
      'formViagem.destination': 'Destination',
      'formViagem.startDate': 'Start date',
      'formViagem.endDate': 'End date',
      'formViagem.budget': 'Budget (R\$)',
      'formViagem.tripType': 'Trip Type',
      'formViagem.preferences': 'Preferences (optional)',
      'formViagem.createBtn': 'Create Trip',
      'formViagem.required': 'Required field',
      'formViagem.invalidValue': 'Invalid value',
      'photos.deleteTitle': 'Delete photo?',
      'photos.deleteDesc': 'This action cannot be undone.',
      'photos.cancel': 'Cancel',
      'photos.delete': 'Delete',
      'photos.empty': 'No photos yet.',
      'photos.hint': 'Tap + to add the first one.',
      'photos.addTooltip': 'Add photo',
      'login.subtitle': 'AI-Powered Travel Planning',
      'login.password': 'Password',
      'login.passwordRequired': 'Password required',
      'login.signIn': 'Sign In',
      'login.noAccount': "Don't have an account? ",
      'login.signUp': 'Sign Up',
      'login.emailInvalid': 'Invalid email',
      'register.title': 'Create Account',
      'register.fullName': 'Full Name',
      'register.minChars': 'Minimum 3 characters',
      'register.min8chars': 'Minimum 8 characters',
      'register.needUppercase': 'Needs an uppercase letter',
      'register.needNumber': 'Needs a number',
      'register.hasAccount': 'Already have an account? ',
      'feed.noPostsYet': 'No posts yet. Be the first!',
      'feed.newPostTooltip': 'New post',
      'feed.createHint': "What's on your travel mind?",
      'feed.share': 'Share',
      'feed.loadError': 'Failed to load the feed. Check your connection.',
      'feed.retry': 'Retry',
      'formViagem.selectDates': 'Please select start and end dates',
      'grupos.openTrip': 'Open trip',
      'grupos.openTripFull': 'Open full trip',
      'grupos.iaHint': 'Ask about the trip...',
      'grupos.iaEmptyHint': 'Ask anything about\nyour trip and destination',
      'grupos.iaError': 'Could not get a response. Please try again.',
      'grupos.chatIA': 'AI Chat',
      'grupos.codeCopied': 'Code copied!',
      'grupos.inviteCode': 'Invite code',
      'grupos.period': 'Period',
      'grupos.budgetLabel': 'Budget',
      'grupos.type': 'Type',
      'grupos.preferencesLabel': 'Preferences',
      'grupos.tbd': 'TBD',
      'grupos.suggest1': 'What to pack for this trip?',
      'grupos.suggest2': 'Budget tips',
      'grupos.suggest3': 'Must-see attractions',
      'grupos.suggest4': 'Best time to go',
      'info.destination': 'Destination',
      'info.period': 'Period',
      'info.budget': 'Budget',
      'info.type': 'Type',
      'info.preferences': 'Preferences',
      'info.aiTipsTitle': 'AI Assistant Tips',
      'info.aiTipsSubtitle': 'Try asking the AI assistant:',
      'info.inviteCode': 'Invite Code',
      'info.codeCopied': 'Code copied!',
      'info.aiTip1': '"What are the best restaurants in [destination]?"',
      'info.aiTip2': '"Suggest a 3-day itinerary for our trip."',
      'info.aiTip3': '"What should we pack for this type of trip?"',
      'info.aiTip4': '"How can we split costs fairly among the group?"',
      'info.aiTip5': '"What are must-see attractions near [destination]?"',
      'info.aiTip6': '"Any local customs or tips we should know?"',
      'cropper.title': 'Crop Photo',
      'cropper.usePhoto': '✓ Use this photo',
      'cropper.cancel': 'Cancel',
    },
  };

  String translate(String key) {
    return translations[_locale.languageCode]?[key] ?? key;
  }
}
