import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class LanguageProvider with ChangeNotifier {
  Locale _locale = const Locale('pt', 'BR');

  Locale get locale => _locale;

  void setLanguage(String languageCode) {
    if (languageCode == 'pt') {
      _locale = const Locale('pt', 'BR');
    } else {
      _locale = const Locale('en', 'US');
    }
    notifyListeners();
  }

  static Map<String, Map<String, String>> translations = {
    'pt': {
      'nav.myTrips': 'Minhas Viagens',
      'nav.groups': 'Grupos',
      'nav.explore': 'Explorar Viagens',
      'explorar.header': 'Explorar Viagens',
      'explorar.searchPlaceholder': '🔎 Pesquisar destino...',
      'explorar.searchBtn': 'Pesquisar',
      'explorar.empty': 'Nenhuma viagem pública ainda. 🌍',
      'explorar.createdBy': 'Criado por:',
      'explorar.participants': 'participantes',
      'explorar.viewTrip': 'Solicitar participação',
      'explorar.full': 'Viagem lotada',
      'explorar.ownTrip': 'Sua viagem',
      'explorar.requestMessagePlaceholder': 'Diga por que quer participar (opcional)...',
      'explorar.myBudget': '💰 Meu orçamento',
      'explorar.myBudgetPlaceholder': 'R\$ 0,00 (opcional)',
      'explorar.invalidBudget': 'Informe um orçamento válido (0 ou mais)',
      'explorar.budgetTotal': 'Orçamento total',
      'explorar.requestSend': 'Enviar',
      'explorar.requestSent': 'Solicitação enviada ✓',
      'explorar.requestError': 'Não foi possível enviar a solicitação',
      'nav.feed': 'Feed',
      'nav.settings': 'Configurações',
      'nav.signOut': 'Sair',
      'common.back': 'Voltar',
      'config.header': '⚙ Configurações',
      'config.subtitle': 'Gerencie as informações da sua conta.',
      'config.changeAccount': 'Mudar informações da conta',
      'config.changeAccountDesc': 'Atualize seu nome, email ou exclua sua conta',
      'config.alterTitle': 'Alterar informações da conta',
      'config.newName': 'Novo nome',
      'config.newEmail': 'Novo email',
      'config.namePlaceholder': 'Seu nome',
      'config.emailPlaceholder': 'seu@email.com',
      'config.saveChanges': 'Salvar alterações',
      'config.saving': 'Salvando...',
      'config.deleteAccount': 'Excluir conta',
      'config.deleteAccountConfirmBody': 'Isso excluirá permanentemente sua conta e todos os seus dados. Essa ação não pode ser desfeita.',
      'config.deleting': 'Excluindo...',
      'config.updateSuccess': 'Usuário atualizado com sucesso!',
      'config.updateError': 'Aconteceu algum erro ao atualizar o usuário. Tente novamente.',
      'config.nameRequired': 'O nome não pode estar vazio.',
      'config.emailInvalid': 'Informe um endereço de e-mail válido.',
      'config.deleteSuccess': 'Usuário deletado com sucesso!',
      'config.deleteError': 'Aconteceu algum erro ao deletar o usuário. Tente novamente.',
      'config.changePassword': 'Alterar senha',
      'config.changePasswordDesc': 'Atualize a senha usada para entrar na sua conta',
      'config.changePasswordTitle': 'Alterar senha',
      'config.currentPassword': 'Senha atual',
      'config.currentPasswordPlaceholder': 'Sua senha atual',
      'config.newPassword': 'Nova senha',
      'config.newPasswordPlaceholder': 'Mínimo de 8 caracteres',
      'config.confirmNewPassword': 'Confirmar nova senha',
      'config.confirmNewPasswordPlaceholder': 'Repita a nova senha',
      'config.savePassword': 'Salvar nova senha',
      'config.currentPasswordRequired': 'Informe sua senha atual.',
      'config.newPasswordRequired': 'Informe uma nova senha.',
      'config.newPasswordTooShort': 'A nova senha deve ter no mínimo 8 caracteres.',
      'config.newPasswordWeak': 'A nova senha deve conter ao menos uma letra maiúscula e um número.',
      'config.newPasswordSameAsCurrent': 'A nova senha deve ser diferente da atual.',
      'config.confirmPasswordRequired': 'Confirme sua nova senha.',
      'config.passwordsDontMatch': 'As senhas não coincidem.',
      'config.currentPasswordIncorrect': 'Senha atual incorreta.',
      'config.passwordUpdateSuccess': 'Senha alterada com sucesso!',
      'config.passwordUpdateError': 'Aconteceu algum erro ao alterar a senha. Tente novamente.',
      'config.language': 'Idioma',
      'config.languageDesc': 'Escolha o idioma de preferência',
      'config.langEn': 'English',
      'config.langPt': 'Português',
      'language.select': 'Idioma',
      'language.pt': 'Português (Brasil)',
      'language.en': 'English (United States)',
      'lobby.greeting': 'Olá, {name}! 👋',
      'lobby.aiAssistant': 'Assistente de Viagem IA',
      'lobby.newTrip': 'Nova Viagem',
      'lobby.noTrips': 'Nenhuma viagem ainda',
      'lobby.createFirst': 'Crie sua primeira viagem',
      'lobby.selectTrip': 'Selecione uma viagem para começar a conversar',
      'lobby.thinking': 'Pensando...',
      'lobby.hint': 'Pergunte qualquer coisa sobre sua viagem...',
      'lobby.nextTrip.label': 'Próxima viagem',
      'lobby.chat.aiLabel': 'IA',
      'lobby.chat.youLabel': 'Você',
      'lobby.chat.selectFirst': 'Selecione uma viagem antes de enviar uma mensagem.',
      'viagem.title': 'Viagem',
      'viagem.error': 'Falha ao carregar dados da viagem.',
      'viagem.retry': 'Tentar novamente',
      'viagem.tabs.overview': 'Visão Geral',
      'viagem.tabs.finances': 'Minhas Finanças',
      'viagem.tabs.admin': 'Admin',
      'viagem.tabs.expenses': 'Gastos',
      'viagem.tabs.itinerary': 'Roteiro',
      'viagem.tabs.photos': 'Fotos',
      'viagem.tabs.chat': 'Chat',
      'viagem.tabs.info': 'Info',
      'viagem.value.placeholder': 'Valor...',
      'viagem.copyCode': '📋 Copiar código de convite',
      'common.copied': 'Copiado!',
      'common.copy': 'Copiar',
      'common.cancel': 'Cancelar',
      'common.error': 'Erro',
      'viagem.infoTitle': 'Informações da viagem',
      'viagem.inviteTitle': 'Convidar pessoas',
      'viagem.inviteDesc': 'Compartilhe este código com seus amigos.',
      'viagem.dashboard': 'Dashboard do Grupo',
      'viagem.budget': 'Orçamento',
      'viagem.budgetTotal': 'Orçamento Total',
      'viagem.consumed': 'consumido',
      'viagem.categories': 'Categorias',
      'viagem.noExpenses': 'Nenhum gasto registrado',
      'viagem.myView': 'Minha Visão',
      'finances.myFinances': 'Meu Financeiro',
      'finances.recent': 'Últimos Gastos',
      'finances.noRecent': 'Sem gastos recentes',
      'finances.myBudget': 'Meu Orçamento',
      'finances.budgetSet': 'Orçamento definido',
      'finances.available': 'Disponível',
      'finances.editBudget': 'Alterar orçamento',
      'finances.budgetPlaceholder': 'R\$ 0,00',
      'finances.budgetError': 'Informe um orçamento válido.',
      'finances.noBudget': 'Não definido',
      'finances.save': 'Salvar',
      'finances.cancel': 'Cancelar',
      'admin.panel': 'Painel Administrativo',
      'admin.itineraryItems': 'Itens no Roteiro',
      'admin.manageMembers': '👥 Gerenciar Membros',
      'admin.you2': '(você)',
      'viagem.badge.owner': 'Dono',
      'viagem.badge.admin': 'Admin',
      'viagem.badge.member': 'Membro',
      'viagem.action.promote': 'Promover',
      'viagem.action.demote': 'Rebaixar',
      'viagem.action.remove': 'Remover',
      'viagem.confirmPromote': 'Promover a admin?',
      'viagem.confirmPromoteBody': 'Este membro passará a poder gerenciar o grupo.',
      'viagem.confirmDemote': 'Remover admin?',
      'viagem.confirmDemoteBody': 'Este membro perderá os poderes de administrador.',
      'viagem.confirmRemove': 'Remover membro?',
      'viagem.confirmRemoveBody': 'Esta pessoa será removida do grupo.',
      'viagem.errorPromote': 'Erro ao promover membro.',
      'viagem.errorDemote': 'Erro ao rebaixar membro.',
      'viagem.errorRemove': 'Erro ao remover membro.',
      'viagem.explore.panel': '✈️ Explorar Viagens',
      'viagem.explore.notPublished': 'Esta viagem ainda não está pública em Explorar Viagens.',
      'viagem.explore.published': 'Publicada',
      'viagem.explore.limitLabel': 'Limite de participantes',
      'viagem.explore.publish': '📢 Tornar viagem pública',
      'viagem.explore.update': 'Atualizar',
      'viagem.explore.unpublish': 'Tornar privada',
      'viagem.explore.limitError': 'Informe um limite válido (1 ou mais).',
      'viagem.explore.errorPublish': 'Erro ao publicar viagem.',
      'viagem.explore.errorUnpublish': 'Erro ao tornar a viagem privada.',
      'viagem.explore.confirmUnpublish': 'Tornar viagem privada?',
      'viagem.explore.confirmUnpublishBody': 'A viagem deixará de aparecer em Explorar Viagens.',
      'viagem.explore.requests': '📥 Solicitações de participação',
      'viagem.explore.noRequests': 'Nenhuma solicitação pendente.',
      'viagem.explore.accept': 'Aceitar',
      'viagem.explore.reject': 'Recusar',
      'viagem.explore.errorRespond': 'Erro ao responder solicitação.',
      'viagem.itinerary.ia.createBtn': '✨ Criar roteiro com IA',
      'viagem.itinerary.ia.regenerateBtn': '✨ Regenerar roteiro com IA',
      'viagem.itinerary.ia.badge': 'IA',
      'viagem.itinerary.ia.step1': 'Analisando o destino...',
      'viagem.itinerary.ia.step2': 'Consultando pontos turísticos...',
      'viagem.itinerary.ia.step3': 'Organizando o roteiro...',
      'viagem.itinerary.ia.step4': 'Quase lá...',
      'viagem.itinerary.ia.error': 'Erro ao gerar roteiro com IA. Tente novamente.',
      'viagem.itinerary.titleError': 'Digite um título para o item.',
      'viagem.itinerary.deleteConfirmTitle': 'Excluir item do roteiro?',
      'viagem.itinerary.deleteConfirmBody': 'Essa ação não pode ser desfeita.',
      'viagem.itinerary.deleteConfirmBtn': 'Excluir',
      'viagem.groupChat': '💬 Chat do Grupo',
      'viagem.chatPlaceholder': 'Escreva uma mensagem...',
      'viagem.settings.title': '⚙️ Configurações da viagem',
      'viagem.settings.name': 'Nome',
      'viagem.settings.destination': 'Destino',
      'viagem.settings.startDate': 'Data de início',
      'viagem.settings.endDate': 'Data de término',
      'viagem.settings.type': 'Tipo de viagem',
      'viagem.settings.preferences': 'Descrição / preferências',
      'viagem.settings.save': 'Salvar alterações',
      'viagem.settings.fillRequired': 'Preencha todos os campos obrigatórios.',
      'viagem.settings.datesOrder': 'A data de fim deve ser posterior à data de início.',
      'viagem.settings.datesPast': 'As datas não podem estar no passado.',
      'viagem.settings.destinationChangeTitle': 'Alterar dados da viagem?',
      'viagem.settings.destinationChangeBody': 'Mudar destino, datas, tipo ou preferências pode deixar o roteiro atual incoerente com a viagem.',
      'viagem.settings.destinationChangeConfirm': 'Salvar mesmo assim',
      'viagem.settings.saved': 'Alterações salvas com sucesso!',
      'viagem.settings.error': 'Erro ao salvar alterações.',
      'viagem.dangerZone': '⚠️ Zona de perigo',
      'viagem.dangerZone.ownerDesc': 'Você é o dono desta viagem. Excluí-la remove tudo permanentemente para todos os membros.',
      'viagem.dangerZone.memberDesc': 'Você pode sair desta viagem a qualquer momento.',
      'viagem.leaveTrip': '🚪 Sair da viagem',
      'viagem.deleteTrip': '🗑 Excluir viagem',
      'viagem.leaveConfirmTitle': 'Sair da viagem?',
      'viagem.leaveConfirmBody': 'Você precisará de um novo convite para voltar a participar.',
      'viagem.leaveError': 'Erro ao sair da viagem.',
      'viagem.deleteConfirmTitle': 'Excluir viagem?',
      'viagem.deleteConfirmBody': 'Essa ação é permanente e remove a viagem para todos os membros.',
      'viagem.deleteError': 'Erro ao excluir viagem.',
      'viagem.confirmDeleteExpense': 'Excluir gasto?',
      'viagem.confirmDeleteExpenseBody': 'Essa ação não pode ser desfeita.',
      'viagem.cat.transporte': '🚗 Transporte',
      'viagem.cat.alimentacao': '🍽️ Alimentação',
      'viagem.cat.hospedagem': '🏨 Hospedagem',
      'viagem.cat.lazer': '🎭 Lazer',
      'viagem.cat.compras': '🛍️ Compras',
      'viagem.cat.saude': '💊 Saúde',
      'viagem.cat.outro': '📦 Outro',
      'viagem.registerExpense': 'Registrar Gasto',
      'viagem.registerBtn': 'Registrar gasto',
      'viagem.saving': 'Salvando...',
      'viagem.expenseError': 'Informe um valor válido.',
      'viagem.history': 'Histórico do grupo',
      'viagem.emptyExpenses': 'Nenhum gasto registrado ainda.',
      'viagem.itineraryTitle': 'Roteiro da Viagem',
      'expenses.edit': 'Editar Gasto',
      'expenses.value': 'Valor (R\$)',
      'expenses.category': 'Categoria',
      'expenses.description': 'Descrição',
      'expenses.descriptionHint': 'Descrição (opcional)',
      'expenses.cancel': 'Cancelar',
      'expenses.save': 'Salvar',
      'expenses.date': 'Data',
      'expenses.dateRangeHint': 'Válido entre',
      'expenses.splitWith': 'Dividir com:',
      'expenses.splitNone': 'Ninguém selecionado → dividir igualmente entre todos os {count} membros',
      'expenses.splitSelected': 'Dividindo entre {count} membro(s) selecionado(s)',
      'expenses.add': 'Adicionar Gasto',
      'expenses.empty': 'Nenhum gasto ainda.',
      'expenses.deleteError': 'Erro ao deletar gasto: {error}',

      'admin.required': 'Acesso de administrador necessário',
      'admin.statistics': 'Estatísticas',
      'admin.activeMembers': 'Membros Ativos',
      'admin.photos': 'Fotos',
      'admin.itinerary': 'Roteiro',
      'admin.ranking': 'Ranking Financeiro',
      'admin.members': 'Membros',
      'admin.promote': 'Promover a admin',
      'admin.demote': 'Remover admin',
      'admin.you': 'Você',
      'overview.totalSpent': 'Total Gasto',
      'overview.remainingBudget': 'Orçamento Restante',
      'overview.used': 'usado',
      'overview.byCategory': 'Por Categoria',
      'finances.paid': 'Eu paguei',
      'finances.debt': 'Minha dívida',
      'finances.recentExpenses': 'Gastos Recentes',
      'itinerary.add': 'Adicionar Item',
      'itinerary.edit': 'Editar Item',
      'itinerary.title': 'Título',
      'itinerary.description': 'Descrição',
      'itinerary.cancel': 'Cancelar',
      'itinerary.save': 'Salvar',
      'itinerary.empty': 'Nenhum item no roteiro ainda.',
      'chat.hint': 'Mensagem...',
      'chat.thinking': 'Pensando...',
      'perfil.myProfile': 'Meu Perfil',
      'perfil.profile': 'Perfil',
      'perfil.posts': 'Postagens',
      'perfil.followers': 'Seguidores',
      'perfil.following': 'Seguindo',
      'perfil.follow': 'Seguir',
      'perfil.followingBtn': 'Seguindo',
      'perfil.editProfile': 'Editar Perfil',
      'perfil.cancel': 'Cancelar',
      'perfil.save': 'Salvar',
      'perfil.name': 'Nome',
      'perfil.bio': 'Bio',
      'perfil.addBio': 'Adicione uma bio...',
      'perfil.memberSince': 'Membro desde',
      'perfil.noPosts': 'Nenhuma postagem ainda.',
      'perfil.deletePost': 'Excluir post',
      'perfil.comments': 'Comentários',
      'perfil.like': 'curtida',
      'perfil.likes': 'curtidas',
      'perfil.addComment': 'Adicionar um comentário...',
      'perfil.post': 'Publicar',
      'perfil.noUsers': 'Nenhum usuário ainda.',
      'feed.addComment': 'Escreva um comentário...',
      'feed.viewAll': 'Ver todos os {count} comentário(s)',
      'grupos.title': 'Grupos',
      'grupos.newTrip': 'Nova Viagem',
      'grupos.joinTitle': 'Entrar em um grupo',
      'grupos.joinDesc': 'Digite o código de convite para entrar em uma viagem existente.',
      'grupos.joinPlaceholder': 'Código de convite (ex: AB12CD)',
      'grupos.joinBtn': 'Entrar',
      'grupos.search': 'Pesquisar grupos...',
      'grupos.searchResults': 'Resultados da Busca',
      'grupos.myTrips': 'Minhas Viagens',
      'grupos.yourGroups': 'Seus grupos',
      'grupos.tapHint': 'Toque para abrir a viagem  ·  Segure para detalhes',
      'grupos.noGroups': 'Nenhum grupo encontrado.',
      'grupos.empty': 'Você não pertence a nenhum grupo ainda.\nCrie uma viagem ou entre pelo código acima.',
      'grupos.enterCodeError': 'Informe o código de convite.',
      'grupos.joinError': 'Erro ao entrar no grupo.',
      'grupos.viewTrip': 'Ver viagem',
      'grupos.chat': '💬 Chat',
      'grupos.joinSuccess': 'Entrou no grupo com sucesso!',
      'formViagem.name': 'Nome da viagem',
      'formViagem.name.placeholder': 'ex: Europa Verão 2025',
      'formViagem.city': 'Cidade',
      'formViagem.cityPlaceholder': 'ex: Paris',
      'formViagem.start': 'Data de início',
      'formViagem.end': 'Data de fim',
      'formViagem.budget': 'Seu orçamento (R\$)',
      'formViagem.type': 'Tipo de viagem',
      'formViagem.type.gastronomic': 'Gastronômico',
      'formViagem.type.adventure': 'Aventura',
      'formViagem.type.cultural': 'Cultural',
      'formViagem.type.relax': 'Relaxamento',
      'formViagem.prefs.label': 'Preferências',
      'formViagem.prefs.placeholder': 'ex: museus, restaurantes...',
      'formViagem.invalidBudget': 'Informe um orçamento válido (ex: 3000.00).',
      'formViagem.error': 'Erro ao criar viagem.',
      'formViagem.serverError': 'Erro ao conectar com servidor.',
      'formViagem.success': 'Viagem criada com sucesso!',
      'chatViagem.title': '💬 Chat de Viagem IA',
      'chatViagem.header': '🤖 Assistente Diartrip',
      'chatViagem.intro': 'Olá! Sou a assistente da Diartrip. Vou te fazer algumas perguntas rápidas para montar sua viagem — vamos começar! ✈️',
      'chatViagem.ask.nome': 'Qual o nome dessa viagem?',
      'chatViagem.ask.destino': 'Para onde vocês vão?',
      'chatViagem.ask.dataInicio': 'Quando a viagem começa?',
      'chatViagem.ask.dataFim': 'E quando ela termina?',
      'chatViagem.ask.participantes': 'Quantas pessoas vão? (opcional)',
      'chatViagem.ph.participantes': 'ex: 4',
      'chatViagem.ask.orcamento': 'Qual o orçamento total da viagem? (R\$)',
      'chatViagem.ask.transporte': 'Como vocês vão se deslocar? (opcional — avião, carro, ônibus...)',
      'chatViagem.ph.transporte': 'ex: Avião',
      'chatViagem.ask.tipo': 'Qual estilo combina mais com essa viagem?',
      'chatViagem.ask.preferencias': 'Mais alguma preferência ou interesse? (opcional — praia, gastronomia, natureza, aventura...)',
      'chatViagem.skip': 'Pular',
      'chatViagem.summary.title': 'Aqui está o resumo da sua viagem:',
      'chatViagem.summary.participants': 'Participantes',
      'chatViagem.summary.transport': 'Transporte',
      'chatViagem.summary.confirm': 'Posso criar essa viagem?',
      'chatViagem.confirmBtn': '✅ Confirmar e criar',
      'chatViagem.editBtn': '✏️ Corrigir algo',
      'chatViagem.editPick': 'Qual campo você quer corrigir?',
      'chatViagem.creating': 'Criando sua viagem...',
      'chatViagem.errNome': 'Digite um nome para a viagem.',
      'chatViagem.errDestino': 'Digite um destino.',
      'chatViagem.errData': 'Informe uma data válida (não pode ser no passado).',
      'chatViagem.errDataFim': 'A data de fim deve ser depois da data de início.',
      'chatViagem.none': 'Não informado',
      'photos.deleteTitle': 'Excluir foto?',
      'photos.deleteDesc': 'Essa ação não pode ser desfeita.',
      'photos.cancel': 'Cancelar',
      'photos.delete': 'Excluir',
      'photos.empty': 'Nenhuma foto ainda.',
      'photos.hint': 'Toque + para adicionar a primeira.',
      'photos.addTooltip': 'Adicionar foto',
      'login.title': 'Login',
      'login.subtitle': 'Planejamento de Viagens com IA',
      'login.password': 'Senha',
      'login.passwordRequired': 'Digite a senha',
      'login.signIn': 'Entrar',
      'login.noAccount': 'Não tem uma conta? ',
      'login.signUp': 'Cadastrar-se',
      'login.emailInvalid': 'E-mail inválido',
      'register.title': 'Cadastro',
      'register.name.label': 'Nome',
      'register.name.placeholder': 'Digite seu nome',
      'register.email.placeholder': 'Digite seu email',
      'register.pass.placeholder': 'Crie uma senha',
      'register.pass.hint': 'Mínimo 8 caracteres, com ao menos uma letra maiúscula e um número.',
      'register.submit': 'Criar conta',
      'register.creating': 'Criando...',
      'register.err.name': 'Nome deve ter pelo menos 3 caracteres.',
      'register.err.email': 'Email inválido.',
      'register.err.passLen': 'Senha deve ter no mínimo 8 caracteres.',
      'register.err.passUpper': 'A senha deve conter ao menos uma letra maiúscula.',
      'register.err.passNum': 'A senha deve conter ao menos um número.',
      'register.err.emailTaken': 'Este email já está cadastrado.',
      'register.err.create': 'Erro ao criar conta. Tente novamente.',
      'register.err.autoLogin': 'Conta criada, mas não foi possível fazer login automático.',
      'register.err.connect': 'Não foi possível conectar ao servidor.',
      'register.hasAccount': 'Já tem uma conta? ',
      'feed.header': 'Feed',
      'feed.placeholder': 'Compartilhe algo sobre sua viagem...',
      'feed.photo': 'Foto',
      'feed.publish': 'Publicar',
      'feed.empty': 'Nenhum post ainda. Seja o primeiro! 🌍',
      'feed.date.now': 'agora mesmo',
      'feed.date.min': ' min atrás',
      'feed.date.hour': ' h atrás',
      'feed.date.days': ' dias atrás',
      'feed.confirmDelete': 'Excluir este post?',
      'feed.confirmDeleteBody': 'Este post será removido permanentemente.',
      'common.delete': 'Excluir',
      'feed.loadError': 'Erro ao carregar o feed. Verifique sua conexão.',
      'feed.retry': 'Tentar novamente',
      'grupos.openTrip': 'Abrir viagem',
      'grupos.openTripFull': 'Abrir viagem completa',
      'grupos.iaHint': 'Pergunte sobre a viagem...',
      'grupos.iaEmptyHint': 'Pergunte qualquer coisa sobre\nsua viagem e o destino',
      'grupos.iaError': 'Não foi possível obter resposta. Tente novamente.',
      'grupos.chatIA': 'Chat IA',
      'grupos.codeCopied': 'Código copiado!',
      'grupos.inviteCode': 'Código de convite',
      'grupos.period': 'Período',
      'grupos.budgetLabel': 'Orçamento',
      'grupos.type': 'Tipo',
      'grupos.preferencesLabel': 'Preferências',
      'grupos.tbd': 'a definir',
      'grupos.suggest1': 'O que levar nessa viagem?',
      'grupos.suggest2': 'Dicas de orçamento',
      'grupos.suggest3': 'Pontos turísticos imperdíveis',
      'grupos.suggest4': 'Melhor época para ir',
      'info.destination': 'Destino',
      'info.period': 'Período',
      'info.budget': 'Orçamento',
      'info.type': 'Tipo',
      'info.preferences': 'Preferências',
      'info.aiTipsTitle': 'Dicas do Assistente IA',
      'info.aiTipsSubtitle': 'Experimente perguntar ao assistente:',
      'info.inviteCode': 'Código de convite',
      'info.codeCopied': 'Código copiado!',
      'info.aiTip1': '"Quais são os melhores restaurantes em [destino]?"',
      'info.aiTip2': '"Sugira um roteiro de 3 dias para nossa viagem."',
      'info.aiTip3': '"O que devemos levar para esse tipo de viagem?"',
      'info.aiTip4': '"Como podemos dividir os custos de forma justa no grupo?"',
      'info.aiTip5': '"Quais atrações imperdíveis há perto de [destino]?"',
      'info.aiTip6': '"Alguma dica de costumes locais que devemos saber?"',
      'cropper.title': 'Recortar Foto',
      'cropper.usePhoto': '✓ Usar esta foto',
      'cropper.cancel': 'Cancelar',
    },
    'en': {
      'nav.myTrips': 'My Trips',
      'nav.groups': 'Groups',
      'nav.explore': 'Explore Trips',
      'explorar.header': 'Explore Trips',
      'explorar.searchPlaceholder': '🔎 Search destination...',
      'explorar.searchBtn': 'Search',
      'explorar.empty': 'No public trips yet. 🌍',
      'explorar.createdBy': 'Created by:',
      'explorar.participants': 'participants',
      'explorar.viewTrip': 'Request to join',
      'explorar.full': 'Trip full',
      'explorar.ownTrip': 'Your trip',
      'explorar.requestMessagePlaceholder': 'Say why you want to join (optional)...',
      'explorar.myBudget': '💰 My budget',
      'explorar.myBudgetPlaceholder': 'R\$ 0.00 (optional)',
      'explorar.invalidBudget': 'Enter a valid budget (0 or more)',
      'explorar.budgetTotal': 'Total budget',
      'explorar.requestSend': 'Send',
      'explorar.requestSent': 'Request sent ✓',
      'explorar.requestError': 'Could not send request',
      'nav.feed': 'Feed',
      'nav.settings': 'Settings',
      'nav.signOut': 'Sign Out',
      'common.back': 'Back',
      'config.header': '⚙ Settings',
      'config.subtitle': 'Manage your account information.',
      'config.changeAccount': 'Change account information',
      'config.changeAccountDesc': 'Update your name, email or delete your account',
      'config.alterTitle': 'Change account information',
      'config.newName': 'New name',
      'config.newEmail': 'New email',
      'config.namePlaceholder': 'Your name',
      'config.emailPlaceholder': 'your@email.com',
      'config.saveChanges': 'Save changes',
      'config.saving': 'Saving...',
      'config.deleteAccount': 'Delete account',
      'config.deleteAccountConfirmBody': 'This will permanently delete your account and all your data. This action cannot be undone.',
      'config.deleting': 'Deleting...',
      'config.updateSuccess': 'User updated successfully!',
      'config.updateError': 'An error occurred while updating the user. Try again.',
      'config.nameRequired': 'Name cannot be empty.',
      'config.emailInvalid': 'Please enter a valid email address.',
      'config.deleteSuccess': 'User deleted successfully!',
      'config.deleteError': 'An error occurred while deleting the user. Try again.',
      'config.changePassword': 'Change password',
      'config.changePasswordDesc': 'Update the password used to sign in',
      'config.changePasswordTitle': 'Change password',
      'config.currentPassword': 'Current password',
      'config.currentPasswordPlaceholder': 'Your current password',
      'config.newPassword': 'New password',
      'config.newPasswordPlaceholder': 'Minimum 8 characters',
      'config.confirmNewPassword': 'Confirm new password',
      'config.confirmNewPasswordPlaceholder': 'Repeat the new password',
      'config.savePassword': 'Save new password',
      'config.currentPasswordRequired': 'Enter your current password.',
      'config.newPasswordRequired': 'Enter a new password.',
      'config.newPasswordTooShort': 'The new password must be at least 8 characters long.',
      'config.newPasswordWeak': 'The new password must contain at least one uppercase letter and one number.',
      'config.newPasswordSameAsCurrent': 'The new password must be different from the current one.',
      'config.confirmPasswordRequired': 'Confirm your new password.',
      'config.passwordsDontMatch': 'Passwords do not match.',
      'config.currentPasswordIncorrect': 'Current password is incorrect.',
      'config.passwordUpdateSuccess': 'Password changed successfully!',
      'config.passwordUpdateError': 'An error occurred while changing the password. Try again.',
      'config.language': 'Language',
      'config.languageDesc': 'Choose your preferred language',
      'config.langEn': 'English',
      'config.langPt': 'Português',
      'language.select': 'Language',
      'language.pt': 'Portuguese (Brasil)',
      'language.en': 'English (United States)',
      'lobby.greeting': 'Hello, {name}! 👋',
      'lobby.aiAssistant': 'AI Travel Assistant',
      'lobby.newTrip': 'New Trip',
      'lobby.noTrips': 'No trips yet',
      'lobby.createFirst': 'Create your first trip',
      'lobby.selectTrip': 'Select a trip to start chatting',
      'lobby.thinking': 'Thinking...',
      'lobby.hint': 'Ask anything about your trip...',
      'lobby.nextTrip.label': 'Next trip',
      'lobby.chat.aiLabel': 'AI',
      'lobby.chat.youLabel': 'You',
      'lobby.chat.selectFirst': 'Select a trip before sending a message.',
      'viagem.title': 'Trip',
      'viagem.error': 'Failed to load trip data.',
      'viagem.retry': 'Retry',
      'viagem.tabs.overview': 'Overview',
      'viagem.tabs.finances': 'My Finances',
      'viagem.tabs.admin': 'Admin',
      'viagem.tabs.expenses': 'Expenses',
      'viagem.tabs.itinerary': 'Itinerary',
      'viagem.tabs.photos': 'Photos',
      'viagem.tabs.chat': 'Chat',
      'viagem.tabs.info': 'Info',
      'viagem.value.placeholder': 'Value...',
      'viagem.copyCode': '📋 Copy invite code',
      'common.copied': 'Copied!',
      'common.copy': 'Copy',
      'common.cancel': 'Cancel',
      'common.error': 'Error',
      'viagem.infoTitle': 'Trip information',
      'viagem.inviteTitle': 'Invite people',
      'viagem.inviteDesc': 'Share this code with your friends.',
      'viagem.dashboard': 'Group Dashboard',
      'viagem.budget': 'Budget',
      'viagem.budgetTotal': 'Total Budget',
      'viagem.consumed': 'used',
      'viagem.categories': 'Categories',
      'viagem.noExpenses': 'No expenses registered',
      'viagem.myView': 'My View',
      'finances.myFinances': 'My Finances',
      'finances.recent': 'Recent Expenses',
      'finances.noRecent': 'No recent expenses',
      'finances.myBudget': 'My Budget',
      'finances.budgetSet': 'Budget set',
      'finances.available': 'Available',
      'finances.editBudget': 'Change budget',
      'finances.budgetPlaceholder': 'R\$ 0.00',
      'finances.budgetError': 'Enter a valid budget.',
      'finances.noBudget': 'Not set',
      'finances.save': 'Save',
      'finances.cancel': 'Cancel',
      'admin.panel': 'Admin Panel',
      'admin.itineraryItems': 'Itinerary Items',
      'admin.manageMembers': '👥 Manage Members',
      'admin.you2': '(you)',
      'viagem.badge.owner': 'Owner',
      'viagem.badge.admin': 'Admin',
      'viagem.badge.member': 'Member',
      'viagem.action.promote': 'Promote',
      'viagem.action.demote': 'Demote',
      'viagem.action.remove': 'Remove',
      'viagem.confirmPromote': 'Promote to admin?',
      'viagem.confirmPromoteBody': 'This member will be able to manage the group.',
      'viagem.confirmDemote': 'Remove admin?',
      'viagem.confirmDemoteBody': 'This member will lose admin privileges.',
      'viagem.confirmRemove': 'Remove member?',
      'viagem.confirmRemoveBody': 'This person will be removed from the group.',
      'viagem.errorPromote': 'Error promoting member.',
      'viagem.errorDemote': 'Error demoting member.',
      'viagem.errorRemove': 'Error removing member.',
      'viagem.explore.panel': '✈️ Explore Trips',
      'viagem.explore.notPublished': 'This trip is not public in Explore Trips yet.',
      'viagem.explore.published': 'Published',
      'viagem.explore.limitLabel': 'Participant limit',
      'viagem.explore.publish': '📢 Make trip public',
      'viagem.explore.update': 'Update',
      'viagem.explore.unpublish': 'Make private',
      'viagem.explore.limitError': 'Enter a valid limit (1 or more).',
      'viagem.explore.errorPublish': 'Error publishing trip.',
      'viagem.explore.errorUnpublish': 'Error making the trip private.',
      'viagem.explore.confirmUnpublish': 'Make trip private?',
      'viagem.explore.confirmUnpublishBody': 'The trip will no longer appear in Explore Trips.',
      'viagem.explore.requests': '📥 Participation requests',
      'viagem.explore.noRequests': 'No pending requests.',
      'viagem.explore.accept': 'Accept',
      'viagem.explore.reject': 'Reject',
      'viagem.explore.errorRespond': 'Error responding to request.',
      'viagem.itinerary.ia.createBtn': '✨ Create itinerary with AI',
      'viagem.itinerary.ia.regenerateBtn': '✨ Regenerate itinerary with AI',
      'viagem.itinerary.ia.badge': 'AI',
      'viagem.itinerary.ia.step1': 'Analyzing destination...',
      'viagem.itinerary.ia.step2': 'Checking attractions...',
      'viagem.itinerary.ia.step3': 'Organizing itinerary...',
      'viagem.itinerary.ia.step4': 'Almost there...',
      'viagem.itinerary.ia.error': 'Error generating itinerary with AI. Please try again.',
      'viagem.itinerary.titleError': 'Enter a title for the item.',
      'viagem.itinerary.deleteConfirmTitle': 'Delete itinerary item?',
      'viagem.itinerary.deleteConfirmBody': 'This action cannot be undone.',
      'viagem.itinerary.deleteConfirmBtn': 'Delete',
      'viagem.groupChat': '💬 Group Chat',
      'viagem.chatPlaceholder': 'Write a message...',
      'viagem.settings.title': '⚙️ Trip settings',
      'viagem.settings.name': 'Name',
      'viagem.settings.destination': 'Destination',
      'viagem.settings.startDate': 'Start date',
      'viagem.settings.endDate': 'End date',
      'viagem.settings.type': 'Trip type',
      'viagem.settings.preferences': 'Description / preferences',
      'viagem.settings.save': 'Save changes',
      'viagem.settings.fillRequired': 'Fill in all required fields.',
      'viagem.settings.datesOrder': 'The end date must be after the start date.',
      'viagem.settings.datesPast': 'Dates cannot be in the past.',
      'viagem.settings.destinationChangeTitle': 'Change trip details?',
      'viagem.settings.destinationChangeBody': 'Changing the destination, dates, type or preferences may make the current itinerary inconsistent with the trip.',
      'viagem.settings.destinationChangeConfirm': 'Save anyway',
      'viagem.settings.saved': 'Changes saved successfully!',
      'viagem.settings.error': 'Error saving changes.',
      'viagem.dangerZone': '⚠️ Danger zone',
      'viagem.dangerZone.ownerDesc': 'You own this trip. Deleting it permanently removes everything for all members.',
      'viagem.dangerZone.memberDesc': 'You can leave this trip at any time.',
      'viagem.leaveTrip': '🚪 Leave trip',
      'viagem.deleteTrip': '🗑 Delete trip',
      'viagem.leaveConfirmTitle': 'Leave the trip?',
      'viagem.leaveConfirmBody': "You'll need a new invite to join again.",
      'viagem.leaveError': 'Error leaving the trip.',
      'viagem.deleteConfirmTitle': 'Delete trip?',
      'viagem.deleteConfirmBody': 'This action is permanent and removes the trip for all members.',
      'viagem.deleteError': 'Error deleting the trip.',
      'viagem.confirmDeleteExpense': 'Delete expense?',
      'viagem.confirmDeleteExpenseBody': 'This action cannot be undone.',
      'viagem.cat.transporte': '🚗 Transport',
      'viagem.cat.alimentacao': '🍽️ Food',
      'viagem.cat.hospedagem': '🏨 Lodging',
      'viagem.cat.lazer': '🎭 Leisure',
      'viagem.cat.compras': '🛍️ Shopping',
      'viagem.cat.saude': '💊 Health',
      'viagem.cat.outro': '📦 Other',
      'viagem.registerExpense': 'Register Expense',
      'viagem.registerBtn': 'Register expense',
      'viagem.saving': 'Saving...',
      'viagem.expenseError': 'Enter a valid amount.',
      'viagem.history': 'Group history',
      'viagem.emptyExpenses': 'No expenses registered yet.',
      'viagem.itineraryTitle': 'Trip Itinerary',
      'expenses.edit': 'Edit Expense',
      'expenses.value': 'Value (R\$)',
      'expenses.category': 'Category',
      'expenses.description': 'Description',
      'expenses.descriptionHint': 'Description (optional)',
      'expenses.cancel': 'Cancel',
      'expenses.save': 'Save',
      'expenses.date': 'Date',
      'expenses.dateRangeHint': 'Valid between',
      'expenses.splitWith': 'Split with:',
      'expenses.splitNone': 'No one selected → split equally among all {count} members',
      'expenses.splitSelected': 'Splitting among {count} selected member(s)',
      'expenses.add': 'Add Expense',
      'expenses.empty': 'No expenses yet.',
      'expenses.deleteError': 'Error deleting expense: {error}',
      'admin.required': 'Admin access required',
      'admin.statistics': 'Statistics',
      'admin.activeMembers': 'Active Members',
      'admin.photos': 'Photos',
      'admin.itinerary': 'Itinerary',
      'admin.ranking': 'Financial Ranking',
      'admin.members': 'Members',
      'admin.promote': 'Promote to admin',
      'admin.demote': 'Remove admin',
      'admin.you': 'You',
      'overview.totalSpent': 'Total Spent',
      'overview.remainingBudget': 'Remaining Budget',
      'overview.used': 'used',
      'overview.byCategory': 'By Category',
      'finances.paid': 'I paid',
      'finances.debt': 'My debt',
      'finances.recentExpenses': 'Recent Expenses',
      'itinerary.add': 'Add Item',
      'itinerary.edit': 'Edit Item',
      'itinerary.title': 'Title',
      'itinerary.description': 'Description',
      'itinerary.cancel': 'Cancel',
      'itinerary.save': 'Save',
      'itinerary.empty': 'No itinerary items yet.',
      'chat.hint': 'Message...',
      'chat.thinking': 'Thinking...',
      'perfil.myProfile': 'My Profile',
      'perfil.profile': 'Profile',
      'perfil.posts': 'Posts',
      'perfil.followers': 'Followers',
      'perfil.following': 'Following',
      'perfil.follow': 'Follow',
      'perfil.followingBtn': 'Following',
      'perfil.editProfile': 'Edit Profile',
      'perfil.cancel': 'Cancel',
      'perfil.save': 'Save',
      'perfil.name': 'Name',
      'perfil.bio': 'Bio',
      'perfil.addBio': 'Add a bio...',
      'perfil.memberSince': 'Member since',
      'perfil.noPosts': 'No posts yet.',
      'perfil.deletePost': 'Delete post',
      'perfil.comments': 'Comments',
      'perfil.like': 'like',
      'perfil.likes': 'likes',
      'perfil.addComment': 'Add a comment...',
      'perfil.post': 'Post',
      'perfil.noUsers': 'No users yet.',
      'feed.addComment': 'Write a comment...',
      'feed.viewAll': 'View all {count} comment(s)',
      'grupos.title': 'Groups',
      'grupos.newTrip': 'New Trip',
      'grupos.joinTitle': 'Join a group',
      'grupos.joinDesc': 'Enter the invite code to join an existing trip.',
      'grupos.joinPlaceholder': 'Invite code (e.g. AB12CD)',
      'grupos.joinBtn': 'Join',
      'grupos.search': 'Search groups...',
      'grupos.searchResults': 'Search Results',
      'grupos.myTrips': 'My Trips',
      'grupos.yourGroups': 'Your groups',
      'grupos.tapHint': 'Tap to open the trip  ·  Hold for trip details',
      'grupos.noGroups': 'No groups found.',
      'grupos.empty': "You don't belong to any group yet.\nCreate a trip or enter with the code above.",
      'grupos.enterCodeError': 'Enter the invite code.',
      'grupos.joinError': 'Error joining the group.',
      'grupos.viewTrip': 'View trip',
      'grupos.chat': '💬 Chat',
      'grupos.joinSuccess': 'Joined the group successfully!',
      'formViagem.name': 'Trip name',
      'formViagem.name.placeholder': 'e.g. Europe Summer 2025',
      'formViagem.city': 'City',
      'formViagem.cityPlaceholder': 'e.g. Paris',
      'formViagem.start': 'Start date',
      'formViagem.end': 'End date',
      'formViagem.budget': 'Your budget (R\$)',
      'formViagem.type': 'Trip type',
      'formViagem.type.gastronomic': 'Gastronomic',
      'formViagem.type.adventure': 'Adventure',
      'formViagem.type.cultural': 'Cultural',
      'formViagem.type.relax': 'Relaxation',
      'formViagem.prefs.label': 'Preferences',
      'formViagem.prefs.placeholder': 'e.g. museums, restaurants...',
      'formViagem.invalidBudget': 'Enter a valid budget (e.g. 3000.00).',
      'formViagem.error': 'Error creating trip.',
      'formViagem.serverError': 'Error connecting to server.',
      'formViagem.success': 'Trip created successfully!',
      'chatViagem.title': '💬 AI Trip Chat',
      'chatViagem.header': '🤖 Diartrip Assistant',
      'chatViagem.intro': "Hi! I'm the Diartrip assistant. I'll ask a few quick questions to set up your trip — let's start! ✈️",
      'chatViagem.ask.nome': "What's the name of this trip?",
      'chatViagem.ask.destino': 'Where are you headed?',
      'chatViagem.ask.dataInicio': 'When does the trip start?',
      'chatViagem.ask.dataFim': 'And when does it end?',
      'chatViagem.ask.participantes': 'How many people are going? (optional)',
      'chatViagem.ph.participantes': 'e.g. 4',
      'chatViagem.ask.orcamento': "What's the total budget for the trip? (R\$)",
      'chatViagem.ask.transporte': 'How will you get there? (optional — plane, car, bus...)',
      'chatViagem.ph.transporte': 'e.g. Plane',
      'chatViagem.ask.tipo': 'What style fits this trip best?',
      'chatViagem.ask.preferencias': 'Any other preferences or interests? (optional — beach, food, nature, adventure...)',
      'chatViagem.skip': 'Skip',
      'chatViagem.summary.title': "Here's a summary of your trip:",
      'chatViagem.summary.participants': 'Participants',
      'chatViagem.summary.transport': 'Transport',
      'chatViagem.summary.confirm': 'Shall I create this trip?',
      'chatViagem.confirmBtn': '✅ Confirm and create',
      'chatViagem.editBtn': '✏️ Fix something',
      'chatViagem.editPick': 'Which field would you like to change?',
      'chatViagem.creating': 'Creating your trip...',
      'chatViagem.errNome': 'Please enter a name for the trip.',
      'chatViagem.errDestino': 'Please enter a destination.',
      'chatViagem.errData': 'Enter a valid date (not in the past).',
      'chatViagem.errDataFim': 'The end date must be after the start date.',
      'chatViagem.none': 'Not informed',
      'photos.deleteTitle': 'Delete photo?',
      'photos.deleteDesc': 'This action cannot be undone.',
      'photos.cancel': 'Cancel',
      'photos.delete': 'Delete',
      'photos.empty': 'No photos yet.',
      'photos.hint': 'Tap + to add the first one.',
      'photos.addTooltip': 'Add photo',
      'login.title': 'Login',
      'login.subtitle': 'AI-Powered Travel Planning',
      'login.password': 'Password',
      'login.passwordRequired': 'Password required',
      'login.signIn': 'Sign In',
      'login.noAccount': "Don't have an account? ",
      'login.signUp': 'Sign Up',
      'login.emailInvalid': 'Invalid email',
      'register.title': 'Sign Up',
      'register.name.label': 'Name',
      'register.name.placeholder': 'Enter your name',
      'register.email.placeholder': 'Enter your email',
      'register.pass.placeholder': 'Create a password',
      'register.pass.hint': 'Minimum 8 characters, with at least one uppercase letter and one number.',
      'register.submit': 'Create Account',
      'register.creating': 'Creating...',
      'register.err.name': 'Name must be at least 3 characters.',
      'register.err.email': 'Invalid email.',
      'register.err.passLen': 'Password must be at least 8 characters.',
      'register.err.passUpper': 'Password must contain at least one uppercase letter.',
      'register.err.passNum': 'Password must contain at least one number.',
      'register.err.emailTaken': 'This email is already registered.',
      'register.err.create': 'Error creating account. Please try again.',
      'register.err.autoLogin': 'Account created, but automatic login failed.',
      'register.err.connect': 'Could not connect to server.',
      'register.hasAccount': 'Already have an account? ',
      'feed.header': 'Feed',
      'feed.placeholder': 'Share something about your trip...',
      'feed.photo': 'Photo',
      'feed.publish': 'Publish',
      'feed.empty': 'No posts yet. Be the first! 🌍',
      'feed.date.now': 'just now',
      'feed.date.min': ' min ago',
      'feed.date.hour': ' h ago',
      'feed.date.days': ' days ago',
      'feed.confirmDelete': 'Delete this post?',
      'feed.confirmDeleteBody': 'This post will be permanently removed.',
      'common.delete': 'Delete',
      'feed.loadError': 'Failed to load the feed. Check your connection.',
      'feed.retry': 'Retry',
      'grupos.openTrip': 'Open trip',
      'grupos.openTripFull': 'Open full trip',
      'grupos.iaHint': 'Ask about the trip...',
      'grupos.iaEmptyHint': 'Ask anything about\nyour trip and destination',
      'grupos.iaError': 'Could not get a response. Please try again.',
      'grupos.chatIA': 'AI Chat',
      'grupos.codeCopied': 'Code copied!',
      'grupos.inviteCode': 'Invite code',
      'grupos.period': 'Period',
      'grupos.budgetLabel': 'Budget',
      'grupos.type': 'Type',
      'grupos.preferencesLabel': 'Preferences',
      'grupos.tbd': 'TBD',
      'grupos.suggest1': 'What to pack for this trip?',
      'grupos.suggest2': 'Budget tips',
      'grupos.suggest3': 'Must-see attractions',
      'grupos.suggest4': 'Best time to go',
      'info.destination': 'Destination',
      'info.period': 'Period',
      'info.budget': 'Budget',
      'info.type': 'Type',
      'info.preferences': 'Preferences',
      'info.aiTipsTitle': 'AI Assistant Tips',
      'info.aiTipsSubtitle': 'Try asking the AI assistant:',
      'info.inviteCode': 'Invite Code',
      'info.codeCopied': 'Code copied!',
      'info.aiTip1': '"What are the best restaurants in [destination]?"',
      'info.aiTip2': '"Suggest a 3-day itinerary for our trip."',
      'info.aiTip3': '"What should we pack for this type of trip?"',
      'info.aiTip4': '"How can we split costs fairly among the group?"',
      'info.aiTip5': '"What are must-see attractions near [destination]?"',
      'info.aiTip6': '"Any local customs or tips we should know?"',
      'cropper.title': 'Crop Photo',
      'cropper.usePhoto': '✓ Use this photo',
      'cropper.cancel': 'Cancel',
    },
  };

  String translate(String key) {
    return translations[_locale.languageCode]?[key] ?? key;
  }
}
